### PR TITLE
feat: support react portal into iframe

### PR DESCRIPTION
**Pull request by SimeonC**
For related react-helmet issue see https://github.com/nfl/react-helmet/pull/278.

In my case this will be used to inject scripts/styles into the iframe instead of the parent window.

### CODE REVIEW

**Comment by SimeonC** [comment]
@staylor Any chance of a review or being able to merge this in?

**Comment by mbrevda** [comment]
Supporting iframes in a portal would be amazing!

**Comment by mbrevda** [comment]
Wondering why this was closed?

**Comment by olimsaidov** [comment]
@staylor Hello! Why this was closed?

**Pull request closed without merging**
