### PR TITLE
Add ssrOnly as a prop to HelmetProvider

### PR DESCRIPTION
**Pull request by chenxsan**
This pull request add a static `disableHelmetAttribute` to `Provider`, so we can disable `data-rh="true"` server side.

### CODE REVIEW

**Comment by staylor** [comment]
I'm curious  what the implications of this are...? when transitioning between routes in single-page app mode with `react-router` or the like, do the tags still transition properly? do we end up with dupe tags?

**Comment by chenxsan** [comment]
In my use case, I'm only use `react-helmet-async` on server side, won't use it on client side.

**Comment by staylor** [comment]
I'd prefer to see this work by passing `ssrOnly` as a prop to `<HelmetProvider>`

**Comment by chenxsan** [comment]
@staylor Updated.

**Comment by staylor** [comment]
@chenxsan no, I meant `<HelmetProvider ssrOnly context={helmetContext}>...`

**Comment by chenxsan** [comment]
@staylor haha, sorry for misunderstanding. I'll see if I can make it.

**Comment by L42y** [comment]
Why this PR was discontinued? It’s super useful.

**Comment by chenxsan** [comment]
@L42y I don't use this package in my project https://github.com/OkMarvin/okmarvin/commit/faa9deb1a35b02591de267eca12dbdc5fbb8e09e any more.

**Comment by halfzebra** [comment]
@staylor Hi Scott! Are you open to the idea of re-introducing the functionality from this PR?

**Comment by a-tonchev** [comment]
@chenxsan what are you using instead?

**Pull request closed without merging**
