### PR TITLE
Type Update

### PR DESCRIPTION
**Pull request by visormatt**
This PR is just updating the Type Definition noted in [this Issue](https://github.com/staylor/react-helmet-async/issues/68). Let me know what else I can do, thanks!

### CODE REVIEW

**Comment by bke-daniel** [comment]
Thank you @visormatt!

Can we get this merged, please? Currently, our automatic builds are broken, because of this.

**Comment by visormatt** [comment]
@bke-daniel a good work around for now is pin the package (remove the caret `^`) in your `package.json` and regenerate the lock file, short term 🤷‍♂

**Comment by psaia** [comment]
Thanks @visormatt. Looking forward to this merge!

**Comment by pzi** [comment]
### :shipit: 🙏

**Pull request merged**
