### PR TITLE
Add React import in index.d.ts

### PR DESCRIPTION
**Pull request by yowakita**
PR to fix issue #40

### CODE REVIEW

**Comment by staylor** [comment]
Thanks!

**Comment by ekilah** [comment]
@staylor @yowakita this change produces errors for me because of the way React is imported. in my project I always import it as `import * as React from 'react'` rather than `import React from 'react'`. I'm not sure if maybe React changed the way their default export works or what, i'm on React 16.9. Is this affecting anyone else?

**Comment by ekilah** [comment]
Maybe  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33097 provides more context. I don't have `allowSyntheticDefaultImports` enabled

**Comment by ekilah** [comment]
Ah, I'm dumb. https://github.com/staylor/react-helmet-async/commit/3802f7abbf42abab258799cc65a30d67ea2d6bf0 already fixed this (saw when I forked to fix it myself). Can this change be published? 😄

**Pull request merged**
